name: Test

on:
  workflow_dispatch:

jobs:
  run-test:
    name: Run Test
    runs-on: macos-14
    timeout-minutes: 20
    env:
      DEVELOPER_DIR: "/Applications/Xcode_15.4.app/Contents/Developer"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Show Xcode Version
        run: xcodebuild -version

      - name: Run Test
        run: |
          xcodebuild test \
          -scheme LicenseChecker \
          -destination "platform=macOS" \
          -resultBundlePath TestsResult | \
          xcpretty -c && exit ${PIPESTATUS[0]}

      - name: Archive unit test results
        if: success() || failure()
        uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: TestsResult.xcresult
